config/routes.rb
JordanBlog::Application.routes.draw do
  
  devise_for :users
  resources :posts do 
    resources :comments, only: [:new, :create]
  end

  resources :categories, except: [:show, :edit]
  get '/blog_admin' => 'blog_admin#blog_admin', :as => :blog_admin
  get '/about' => 'static_pages#about', :as => :about
  get '/archives' => 'static_pages#archives', :as => :archives


  root :to => "posts#index" 
end

app/models/category.rb
class Category < ActiveRecord::Base

has_and_belongs_to_many :posts

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base

belongs_to :user
has_and_belongs_to_many :categories
has_many :comments, :dependent => :destroy

validates_presence_of :body, :title


  def add_categories(params)
    params.each do |cat|
      self.categories << Category.find(cat.to_i)
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
end

app/controllers/blog_admin_controller.rb
class BlogAdminController < ApplicationController
  
  before_filter :authenticate_user!
  
  def blog_admin
    if current_user
      user = User.find(current_user.id)
      if administrator?(user)
        @posts = Post.all
        @category = Category.new
        render :blog_admin
      else
        flash[:alert] = "Only Administrators can access that page."
        redirect_to root_path
        flash[:alert] = "Only Administrators can access this page."

      end
    else
      redirect_to new_user_session_path
    end
  end

  protected 

  def administrator?(user)
    user.email == "jpluftig@hotmail.com"
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  respond_to :html, :js

def index
  @category = Category.new
  @categories = Category.all
end

def new
  @category = Category.new
end

def create
  @category = Category.create!(category_params)
  respond_to do |format|
    format.html { redirect_to categories_path }
    format.js
  end
end

def destroy
  @category = Category.destroy(params[:id])
  respond_to do |format|
    format.html { redirect_to categories_path }
    format.js
  end
end

private

  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def new
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create!(comment_params)
    respond_to do |format|
      format.html { redirect_to @post }
      format.js
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	http_basic_authenticate_with :name => "jlove", :password => "sexyass"
	
	def index
		@posts = Post.all[0...-1].reverse
		@latest_post = Post.last
		respond_to do |format|
      format.html
      format.json { render json: @posts }
      format.atom
    end
	end

	def show
		@post = Post.find(params[:id])
		@comments = Comment.all
		@comment = Comment.new
	end

	def new
		@post = Post.new
		@categories = Category.all
	end

	def create
		@post = Post.create(title:params[:post][:title], body:params[:post][:body])
		current_user.posts << @post
		if @post.save
			@post.add_categories(params[:post][:category_ids])
			redirect_to @post
		else
			redirect_to root_path
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		@post.update_attributes(title:params[:post][:title], body:params[:post][:body])
		@post.categories.clear
		if @post.save
			@post.add_categories(params[:post][:category_ids])
			redirect_to @post
		else
			redirect_to edit_post_path(@post)
		end
	end

	def destroy
	@post = Post.find(params[:id])
	@post.destroy
	redirect_to blog_admin_path
	end

	private

  # def user_params
  #   params.require(:post).permit()
  # end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	
  def about
  end

  def archives
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def administrator?(user)
    user.email == "jpluftig@hotmail.com"
  end
end

app/views/blog_admin/blog_admin.html.erb
<div class="innerContainer"> 
<% @posts.each do |post| %>
<h3><%= link_to post.title, post_path(post)  %></h3>  
<%= link_to 'Edit', edit_post_path(post) %>
<%= link_to "Delete", post_path(post), method: :delete %>

<% end %>
</div>

app/views/categories/_category.html.erb
<li><%= @category.name %> <%= link_to "Delete", @category, method: :delete %></li>

app/views/categories/_form.html.erb
<%= form_for @category, :html => {:id => "new_category"}, remote: true do |f| %>
 <%= f.label :category_name %><br>
 <%= f.text_field :name %>
 
 <%= f.submit "name" %>
 <% end %>

app/views/categories/create.js.erb
$('#new_category').remove();
$('#new_category_link').show();
$('ul#category_list').append('<%= j render(@category) %>');

app/views/categories/destroy.js.erb
$('.delete_link').bind('ajax:success', function(){
  $(this).closest('li').remove();
});

app/views/categories/index.html.erb
<div class="innerContainer"> 
<%= link_to "Add a Category", new_category_path, id: "new_category_link", remote: true %>
<br><br>

<ul id="category_list">
<% @categories.each do |cat| %>
<li><%= cat.name %>
<%= link_to "Delete", cat, method: :delete, class: "delete_link", remote: true %></li>

<% end %>
</ul>
</div>

app/views/categories/new.html.erb
<%= render 'form' %>

app/views/categories/new.js.erb
$('#new_category_link').hide().after('<%= j render("form") %>')

app/views/comments/_comment.html.erb
<%= div_for comment do %>
  <%= comment.body %>
<% end %>

app/views/comments/_form.html.erb
<%= form_for [@post, @comment], remote: true do |f| %>
  <p>
   <%= f.label :body, "New comment" %><br/>
   <%= f.text_area :body, id: "comment_body" %>
 </p>
 <p><%= f.submit "Add comment", id: 'add_comment_form_button' %></p> 
 <% end %>

app/views/comments/create.js.erb
$('#comments').append('<%= j render(@comment) %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <title>Jordan Luftig's Blog</title>
  <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'shared/navBar' %>
  <div class="col-xs-12" id="head-title">
    <h1>JORDAN LUFTIG</h1>
    <h4>WRITING ABOUT STUFF THAT ACTUALLY MATTERS</h4>
  </div>
  <div class="container">
    <% if flash[:notice] %>
    <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if flash[:alert] %>
    <p class="alert"><%= alert %></p>
    <% end %>
    <% if flash[:error] %>
    <ul>
      <div class="alert"><% flash[:error].each do |error| %>
        <li><%= error %></li>
        <% end %>
      </div>
    </ul>
    <% end %>

    <%= yield %>
  </div>

</body>
</html>

app/views/posts/_post.html.erb
 <h2><%= link_to_unless_current post.title, post %></h2>
 <%= simple_format post.body %>

app/views/posts/edit.html.erb
<div class="innerContainer"> 
 <%= form_for [@post] do |f| %>
 <%= f.label :title %><br>
 <%= f.text_field :title, :style => "width: 1170px"  %><br><br>
 <%= f.label :body %>
 <%= f.text_area :body, :style => "width: 1170px; height: 300px" %><br><br>
 
 <% for category in Category.find(:all) %>
<div>
  <%= check_box_tag "post[category_ids][]", category.id, @post.categories.include?(category) %>
  <%= category.name %>
</div>
 <% end %>
 <br>
 <%= f.submit "Update Post" %>
<% end %>
</div>

app/views/posts/index.html.erb
<div class="inner-container home"> 

  <div class="row featurette">

    <div class="col-md-8">
      <div class="popbox">
        <div>
          <h1 class="featurette-heading"><%= link_to @latest_post.title, post_path(@latest_post) %> <br><span class="text-muted">Awesome catch phrase goes here.</span></h1>
        </div>
      </div>
      <p class="lead"><%= (truncate(@latest_post.body, length: 500)) %><br><%= link_to 'read more', post_path(@latest_post), class: "form-button btn btn-primary" %></p>
    </div>

    <div class="col-md-4 home-image">
      <img class="featurette-image img-responsive" src="http://www.wired.com/images_blogs/design/2013/07/venus-of-google-wallpaper-image_800.jpg" alt="Generic placeholder image">
    </div>

    <div class="post-details col-md-7">
      <div class="col-md-3">
        <% if @latest_post.comments.length > 1 %> 
        <p><%= link_to "#{@latest_post.comments.length} comments ", post_path(@latest_post) %></p>
        <% else %>
        <p><%= link_to "#{@latest_post.comments.length} comment ", post_path(@latest_post) %></p>
        <% end %>
      </div>

      <ul class="col-md-9">
        <% @latest_post.categories.each do |cat| %>
        <li><p class="categories"><%= link_to cat.name, categories_path(cat) %></p><li>
          <% end %>
        </ul>
      </div>
    </div>

  </div>

  <hr class="featurette-divider">
  <div class="row">
    <div class="col-md-8 posts">
      <% @posts.each do |post| %>

      <div class="post col-md-11">
        <div class="post-inner">
          <h2><%= link_to post.title, post_path(post) %></h2>
          <p class="date"><%= post.created_at.strftime("%d %b. %Y")%></p>
          <%= (truncate(post.body, length: 160)) %><br><%= link_to ' read more', post_path(post), class: "form-button btn btn-primary" %>
        </div>

        <div class="post-details">
          <div class="col-md-3">
            <% if post.comments.length > 1 %> 
            <p><%= link_to "#{post.comments.length} comments ", post_path(post) %></p>
            <% else %>
            <p><%= link_to "#{post.comments.length} comment ", post_path(@latest_post) %></p>
            <% end %>
          </div>

          <ul class="col-md-9">
            <% post.categories.each do |cat| %>
            <li><p class="categories"><%= link_to cat.name, categories_path(cat) %></p><li>
              <% end %>
            </ul>
          </div>
        </div>
        <% end %>
      </div>

      <div class="col-md-4 other-stuff">
        <h2>Top 10 Most Liked Posts</h2>
      </div>
    </div>
  </div>

app/views/posts/new.html.erb
<div class="innerContainer"> 
  <div class="col-md-12">
    <%= form_for @post, :html => {:class => "form"} do |f| %>
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control"  %><br><br>
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control",:style => "min-height: 300px"  %>
  </div>
  
  <ul class="col-md-12 categories">
   <% for category in Category.find(:all) %>
      <li><%= check_box_tag "post[category_ids][]", category.id, @post.categories.include?(category) %>
      <%= category.name %></li>
    <% end %>
  </ul>

  <div class="col-md-12 form-button">
    <%= f.submit "Add Post", class: "btn btn-primary" %>
  </div>

  <% end %>

</div>

app/views/posts/show.html.erb
<div class="innerContainer"> 
  <%= render :partial => @post %>
  
  <a id="new_comment_link" href="">Add a Comment </a>
  <br><br>

<div id="comment_form">
<%= render '/comments/form' %>
</div>
  

 <div id="comments">
   <% if @post.comments.length > 0 %>
   <% @post.comments.each do |comment| %>
   <%= comment.body %>
   <br>
   <% end %>
   <% end %>
 </div>




</div>

<script>
  $(document).ready(function(){
    $('#comment_form').hide();
    $('#new_comment_link').on('click', function(e){
      e.preventDefault();
      $('#comment_body').val("");
      $('#new_comment_link').hide();
      $('#comment_form').slideToggle();
    });
    $('#add_comment_form_button').on('click', function(){

      $('#comment_form').slideToggle();
      $('#new_comment_link').show();
    })
  });
</script>

app/views/shared/_navBar.html.erb
<div class="navbar navbar-inverse navbar-fixed-top navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">JL</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav pull-right">
        <li></li>
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'Archives', archives_path %></li>
        <% if user_signed_in? && administrator?(current_user) %>
        <li><%= link_to 'New Post', new_post_path %></li>
        <li><%= link_to 'Admin', blog_admin_path %></li>
        <li><%= link_to 'Categories', categories_path %></li>
        <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </div><!--/.navbar-collapse -->
  </div>
</div>

app/views/static_pages/about.html.erb
<div class="innerContainer"> 
ABOUT PAGE
</div>

app/views/static_pages/archives.html.erb
<div class="innerContainer"> 
ARCHIVES PAGE
</div>

app/views/static_pages/blog_admin.html.erb
<div class="innerContainer"> 
<% @posts.each do |post| %>
<h3><%= link_to post.title, post_path(post)  %></h3>
<%= link_to 'Edit', edit_post_path(post) %>
<%= link_to "Delete", post_path(post), method: :delete %>

<% end %>
</div>